apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.ssp.risk.name }}
  name: {{ .Values.ssp.risk.name }}
spec:
  selector:
    app: {{ .Values.ssp.risk.name }}
  ports:
  - protocol: TCP
    name: web
    port: 8080
    targetPort: 8080
  type: LoadBalancer
